
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const CHANGE_USERNAME='CHANGE_USERNAME';
export const GET_TYPEREQUEST ='GET_TYPEREQUEST';
export const GET_ENDPOINTS = 'GET_ENDPOINTS';

export const GET_APPLICATIONS_ID ='GET_APPLICATIONS_ID'